# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AirMochi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TwilioVideo', '~> 3.0'

  # Pods for AirMochi

end

target 'ScreenStreamer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TwilioVideo', '~> 3.0'

  # Pods for ScreenStreamer

end
